"""rename field url

Revision ID: d0d78fc33da9
Revises: 41aa7a891108
Create Date: 2025-03-17 22:59:54.475236

"""

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import ImageType


# revision identifiers, used by Alembic.
revision = 'd0d78fc33da9'
down_revision = '41aa7a891108'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('filename', sa.String(), nullable=False))
    op.drop_column('contracts', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('contracts', 'filename')
    # ### end Alembic commands ###
