"""s3 storage for contract

Revision ID: ea58c66e18fa
Revises: a048c553d787
Create Date: 2025-03-17 15:53:55.499906

"""

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import ImageType


# revision identifiers, used by Alembic.
revision = 'ea58c66e18fa'
down_revision = 'a048c553d787'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
