"""Добавлен relationship в модель Order

Revision ID: dc6c93160330
Revises: 5bf5b94a9127
Create Date: 2025-03-04 22:38:25.032557

"""

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import ImageType


# revision identifiers, used by Alembic.
revision = 'dc6c93160330'
down_revision = '5bf5b94a9127'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
