"""Добавлен relationship в модель Order

Revision ID: 5bf5b94a9127
Revises: a048c553d787
Create Date: 2025-03-04 22:35:07.278492

"""

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import ImageType


# revision identifiers, used by Alembic.
revision = '5bf5b94a9127'
down_revision = 'a048c553d787'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
