"""new migrations

Revision ID: eec86c49baa5
Revises: 
Create Date: 2025-03-18 01:08:28.536369

"""

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import ImageType


# revision identifiers, used by Alembic.
revision = 'eec86c49baa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'contracts',
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('renter_signature', sa.String(), nullable=True),
        sa.Column('lessor_signature', sa.String(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts')),
    )
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=True)
    op.create_table(
        'orders',
        sa.Column('car_id', sa.Uuid(), nullable=False),
        sa.Column('renter_id', sa.Uuid(), nullable=False),
        sa.Column('lessor_id', sa.Uuid(), nullable=False),
        sa.Column('chat_room_id', sa.Uuid(), nullable=False),
        sa.Column('desired_start_datetime', sa.DateTime(), nullable=False),
        sa.Column('desired_finish_datetime', sa.DateTime(), nullable=False),
        sa.Column('start_rent_datetime', sa.DateTime(), nullable=True),
        sa.Column('finish_rent_datetime', sa.DateTime(), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'UNDER_CONSIDERATION', 'ACCEPTED', 'REJECTED', 'CANCELED', 'IN_PROGRESS', 'FINISHED', name='orderstatus'
            ),
            nullable=False,
        ),
        sa.Column('is_renter_start_order', sa.Boolean(), nullable=False),
        sa.Column('is_lessor_start_order', sa.Boolean(), nullable=False),
        sa.Column('contract_id', sa.UUID(), nullable=True),
        sa.Column('total_price', sa.Numeric(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_orders_contract_id_contracts')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=True)
    op.create_index('ix_orders_lessor_id', 'orders', ['lessor_id'], unique=False, postgresql_using='btree')
    op.create_index('ix_orders_renter_id', 'orders', ['renter_id'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_renter_id', table_name='orders', postgresql_using='btree')
    op.drop_index('ix_orders_lessor_id', table_name='orders', postgresql_using='btree')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
